### ISSUE TITLE
Extension of available raw printing mechanisms

### ISSUE THREAD

**Issue by mike42** [robgridley/zebra#12]
This library currently performs raw printing via a network socket (in `Client.php`), but not all printers have an Ethernet card.

I develop `escpos-php`, which is similar to this library, but outputs a different protocol. That project has accumulated a few different [PrintConnectors](https://github.com/mike42/escpos-php/tree/development/src/Mike42/Escpos/PrintConnectors) over the years, which wrap different raw printing mechanisms so that they can be used from PHP.

We both use the MIT license, `composer` for dependency management, and we both need to be able to deliver raw data to printers. I think it would be a positive if we combine our raw printing code and share a dependency.

If I create a new project for PHP raw printing, would you be open to reviewing a pull request which changes `zebra` to use it?

The specific code changes I would send here would be:

- A `composer.json` change to add the new connector project
- A documentation change to reflect the availability of more raw print mechanisms
- Replacement of `Client` so that it becomes an empty `NetworkPrintConnector` sub-class, avoiding breakage in existing code.
- Moving `CommunicatonException` out of this repo

And the benefit would be:

- Ability to print to Windows shared printers, CUPS, plus things like USB or serial printers which appear as a file on Linux.

**Comment by robgridley** [comment]
Hi, Mike.

I'm not sure how I missed this issue. Sorry about that.

I don't have a problem working with you to support your library, but I won't be eliminating my Client or CommunicationException classes. I wrote this library for a specific purpose, and it is used across several of my own projects.

Let me know how you would like to proceed.
