### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by MatteoVentura** [robgridley/zebra#13]
Hey Rob,

Awesome work!
I was wondering as I am quite new to Zebra printing. Does this code require special drivers for the prints to go through to the printer?

**Comment by StormyCube** [comment]
Hello @MatteoVentura.
I'm not Rob but i can answer that question.
You just need to have enabled the php sockets extension (php_sockets)

**Comment by MatteoVentura** [comment]
Hey, 'not Rob' :P 
Thank you for the answer, that's awesome news!
