### ISSUE TITLE
Fatal error: Class 'Zebra\Zpl\Image' 

### ISSUE THREAD

**Issue by jp911** [robgridley/zebra#6]
Hi,
I am trying to get your code to work.
This is the file structure:
![capture](https://cloud.githubusercontent.com/assets/28704334/26053785/0e6dea24-3962-11e7-9d1a-642654463365.PNG)

I am running index.php from : http://localhost/hs/image/index.php

```
<?php

use Zebra\Client;
use Zebra\Zpl\Image;
use Zebra\Zpl\Builder;

$image = new Image(file_get_contents('example.png'));

$zpl = new Builder();
$zpl->fo(50, 50)->gf($image)->fs();

echo $zpl;


//$client = new Client('10.0.0.50');
//$client->send($zpl);
?>
```

But I keep getting: 
Fatal error: Class 'Zebra\Zpl\Image' not found in C:\wamp64\www\hs\image\index.php on line 7

What am I doing wrong?

**Comment by intrepidws** [comment]
Have you tried being more explicit and specify the path to the image?

**Comment by robgridley** [comment]
It appears you are not using [Composer](https://getcomposer.org/doc/00-intro.md) to [autoload](https://getcomposer.org/doc/01-basic-usage.md#autoloading) the library. You will need to use Composer to manually include each file.

**Comment by jp911** [comment]
Which files do I need to include rob?

**Comment by robgridley** [comment]
I tried manually including the files and it does not work. I guess because the Image interface and Image class have the same name, but different namespaces? The library was designed to be used with Composer.

**Comment by robgridley** [comment]
Based on your screenshot, the following should work:

```php
require 'Zebra/Zpl/Builder.php';
require 'Zebra/Contracts/Zpl/Image.php';
require 'Zebra/Zpl/Image.php';
```

**Comment by jp911** [comment]
that didnt work for me :(

**Comment by jp911** [comment]
ah sorry it did! thank. you
```
<?php

require 'Zebra/Zpl/Builder.php';
require 'Zebra/Contracts/Zpl/Image.php';
require 'Zebra/Zpl/Image.php';

use Zebra\Client;
use Zebra\Zpl\Image;
use Zebra\Zpl\Builder;

$image = new Image(file_get_contents('example.png'));

$zpl = new Builder();
$zpl->fo(50, 50)->gf($image)->fs();

echo $zpl;


//$client = new Client('10.0.0.50');
//$client->send($zpl);
?>
```

**Comment by robgridley** [comment]
Cool. Glad it worked out.
